name: (UPDATE) Solution Version

on:
   workflow_dispatch:
    inputs:
      versionNumber:
        description: Updated Version Number.
        required: true

env:
  metadata_path: 'PackagesLocalDirectory'
  
jobs:
  update_model_version:
    runs-on: [ windows-latest ]

    steps:

      - name: Support longpaths
        run: git config --system core.longpaths true
        
      - name: Cleanup folder        
        continue-on-error: true
        shell: pwsh
        run:  Remove-Item ${{ github.workspace }}\* -Recurse -Force
         
      - uses: actions/checkout@v4.1.1

      - name: Update Version
        shell: pwsh
        run: |
          $versionNumber = "${{ github.event.inputs.versionNumber }}"
          $propsFile = ".\repo.props"
          if ($versionNumber -match "^\d+\.\d+\.\d+\.\d+$")
          {
              $versions = $versionNumber.Split('.')
          }
          else
          {
              throw "Version Number '$versionNumber' is not of format #.#.#.#"
          }
          [xml]$xml = Get-Content $propsFile -Encoding UTF8
          
          $modelInfo = $xml.SelectNodes("/Project")
          if ($modelInfo.Count -eq 1)
          {
              $version = $xml.SelectNodes("/Project/PropertyGroup/MajorVersion")[0]
              $version.InnerText = "$($versions[0]).$($versions[1])"
          
              $version = $xml.SelectNodes("/Project/PropertyGroup/BuildNumber")[0]
              $version.InnerText = "$($versions[2]).$($versions[3])"
          
              $xml.Save($propsFile)
          }
          else
          {
              Write-Host "::Error: - File '$propsFile' is not a valid props file"
          }
           
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4.0.4
        with: 
          branch: gitmvu
          delete-branch: true
          commit-message: "Update ScaleUnit solution to ${{ github.event.inputs.versionNumber }}"
          title: 'Pushing Version Update ${{ github.event.inputs.versionNumber }} into ${{ github.ref }}'
          labels: automated pr    
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>

      - name: auto-pull-request-merge
        uses: KeisukeYamashita/auto-pull-request-merge@v1.0.6
        with:
            checkStatus: false
            pullRequestNumber: ${{ steps.cpr.outputs.pull-request-number }}
            timeoutSeconds: 500
            token: ${{ secrets.REPO_TOKEN }}
            sha: ${{ steps.cpr.outputs.pull-request-head-sha }}
       
      - name: Delete temp branch
        run: |
           git push origin gitmvu --delete
